# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addpath.ui',
# licensing of '.\addpath.ui' applies.
#
# Created: Thu Aug  8 12:58:43 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Addpath(object):
    def setupUi(self, Addpath):
        Addpath.setObjectName("Addpath")
        Addpath.resize(807, 516)
        Addpath.setAcceptDrops(False)
        self.gridLayout = QtWidgets.QGridLayout(Addpath)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonAF = QtWidgets.QPushButton(Addpath)
        self.pushButtonAF.setObjectName("pushButtonAF")
        self.verticalLayout_2.addWidget(self.pushButtonAF)
        self.pushButtonRemove = QtWidgets.QPushButton(Addpath)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.verticalLayout_2.addWidget(self.pushButtonRemove)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonMtoT = QtWidgets.QPushButton(Addpath)
        self.pushButtonMtoT.setObjectName("pushButtonMtoT")
        self.verticalLayout.addWidget(self.pushButtonMtoT)
        self.pushButtonMU = QtWidgets.QPushButton(Addpath)
        self.pushButtonMU.setObjectName("pushButtonMU")
        self.verticalLayout.addWidget(self.pushButtonMU)
        self.pushButtonMD = QtWidgets.QPushButton(Addpath)
        self.pushButtonMD.setObjectName("pushButtonMD")
        self.verticalLayout.addWidget(self.pushButtonMD)
        self.pushButtonMtoB = QtWidgets.QPushButton(Addpath)
        self.pushButtonMtoB.setObjectName("pushButtonMtoB")
        self.verticalLayout.addWidget(self.pushButtonMtoB)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Addpath)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(Addpath)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(Addpath)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listWidget = QtWidgets.QListWidget(Addpath)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.pushButtonSave = QtWidgets.QPushButton(Addpath)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.verticalLayout_3.addWidget(self.pushButtonSave)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Addpath)
        QtCore.QMetaObject.connectSlotsByName(Addpath)

    def retranslateUi(self, Addpath):
        Addpath.setWindowTitle(QtWidgets.QApplication.translate("Addpath", "Add Path", None, -1))
        self.pushButtonAF.setText(QtWidgets.QApplication.translate("Addpath", "Add Folder", None, -1))
        self.pushButtonRemove.setText(QtWidgets.QApplication.translate("Addpath", "Remove", None, -1))
        self.pushButtonMtoT.setText(QtWidgets.QApplication.translate("Addpath", "Move to Top", None, -1))
        self.pushButtonMU.setText(QtWidgets.QApplication.translate("Addpath", "Move Up", None, -1))
        self.pushButtonMD.setText(QtWidgets.QApplication.translate("Addpath", "Move Down", None, -1))
        self.pushButtonMtoB.setText(QtWidgets.QApplication.translate("Addpath", "Move to Bottom", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Addpath", "Command Path", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Addpath", "Notice: 1.Search Priority is defined by Path Order!", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Addpath", "          2. Path (more than 1) should End in hw", None, -1))
        self.pushButtonSave.setText(QtWidgets.QApplication.translate("Addpath", "Save", None, -1))

